import Foundation

/// The full universe of instruments the app knows about.
/// The user's *watchlist* is a subset of these, persisted across launches.
enum MockData {

    static let catalog: [Stock] = [

        // MARK: Individual stocks

        Stock(
            symbol: "AAPL",
            name: "Apple Inc.",
            summary: "American technology company best known for the iPhone, Mac, iPad and services. Listed on NASDAQ; one of the world's most valuable public companies.",
            category: .stock,
            fallbackPrice: 189.20, fallbackChangePercent:  1.24, fallbackCurrency: "USD"
        ),
        Stock(
            symbol: "TSLA",
            name: "Tesla, Inc.",
            summary: "American electric-vehicle and clean-energy company founded by Elon Musk. Designs and manufactures EVs, battery storage and solar products.",
            category: .stock,
            fallbackPrice: 248.50, fallbackChangePercent: -0.83, fallbackCurrency: "USD"
        ),
        Stock(
            symbol: "MSFT",
            name: "Microsoft Corp.",
            summary: "American software giant behind Windows, Microsoft 365, Azure cloud and Xbox. A trillion-dollar enterprise serving consumers and businesses worldwide.",
            category: .stock,
            fallbackPrice: 415.10, fallbackChangePercent:  0.45, fallbackCurrency: "USD"
        ),
        Stock(
            symbol: "NVDA",
            name: "NVIDIA Corp.",
            summary: "American chip designer dominant in GPUs for gaming, professional visualisation, data-centre compute and the AI workloads driving modern machine learning.",
            category: .stock,
            fallbackPrice: 925.10, fallbackChangePercent:  4.52, fallbackCurrency: "USD"
        ),
        Stock(
            symbol: "ASML",
            name: "ASML Holding",
            summary: "Dutch company that manufactures the photolithography machines used by every leading-edge chip foundry. A critical link in the global semiconductor supply chain.",
            category: .stock,
            fallbackPrice: 712.40, fallbackChangePercent:  3.18, fallbackCurrency: "USD"
        ),
        Stock(
            symbol: "SAP.DE", displaySymbol: "SAP",
            name: "SAP SE",
            summary: "German enterprise-software company based in Walldorf. Europe's largest software firm and the global leader in ERP systems used by most Fortune 500 companies.",
            category: .stock,
            fallbackPrice: 192.30, fallbackChangePercent:  2.10, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "ALV.DE", displaySymbol: "ALV",
            name: "Allianz SE",
            summary: "German multinational insurance and asset-management firm headquartered in Munich. One of the world's largest insurers and a major investor in European fixed income.",
            category: .stock,
            fallbackPrice: 263.80, fallbackChangePercent: -1.05, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "SIE.DE", displaySymbol: "SIE",
            name: "Siemens AG",
            summary: "German multinational industrial-technology company based in Munich. Active in automation, electrification, mobility and digital industries software.",
            category: .stock,
            fallbackPrice: 175.40, fallbackChangePercent:  0.62, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "BMW.DE", displaySymbol: "BMW",
            name: "BMW AG",
            summary: "German luxury-vehicle and motorcycle manufacturer headquartered in Munich. Owns the BMW, MINI and Rolls-Royce brands.",
            category: .stock,
            fallbackPrice:  82.10, fallbackChangePercent: -0.41, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "VOW3.DE", displaySymbol: "VOW3",
            name: "Volkswagen AG",
            summary: "German automotive group based in Wolfsburg. One of the largest car manufacturers in the world; owns VW, Audi, Porsche, Škoda, SEAT and Lamborghini.",
            category: .stock,
            fallbackPrice:  96.40, fallbackChangePercent:  1.10, fallbackCurrency: "EUR"
        ),

        // MARK: ETFs popular on Scalable Broker

        Stock(
            symbol: "VWCE.DE", displaySymbol: "VWCE",
            name: "Vanguard FTSE All-World UCITS ETF (Acc)",
            summary: "Globally diversified equity ETF tracking ~3,700 companies across developed and emerging markets. Accumulating share class — dividends reinvested automatically.",
            category: .etf,
            fallbackPrice: 122.50, fallbackChangePercent:  0.85, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "EUNL.DE", displaySymbol: "EUNL",
            name: "iShares Core MSCI World UCITS ETF",
            summary: "Tracks the MSCI World index — about 1,500 large- and mid-cap companies across developed markets. One of the most-held ETFs by European retail investors.",
            category: .etf,
            fallbackPrice:  98.40, fallbackChangePercent:  0.72, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "SXR8.DE", displaySymbol: "SXR8",
            name: "iShares Core S&P 500 UCITS ETF",
            summary: "Tracks the S&P 500 — the 500 largest US public companies. Popular base layer for European retail investors who want US large-cap exposure without buying ADRs.",
            category: .etf,
            fallbackPrice: 552.10, fallbackChangePercent:  1.05, fallbackCurrency: "EUR"
        ),
        Stock(
            symbol: "IS3N.DE", displaySymbol: "IS3N",
            name: "iShares Core MSCI EM IMI UCITS ETF",
            summary: "Tracks the MSCI Emerging Markets IMI index — ~3,000 large-, mid- and small-cap companies across emerging markets. Common diversifier on top of a MSCI World position.",
            category: .etf,
            fallbackPrice:  31.85, fallbackChangePercent: -0.18, fallbackCurrency: "EUR"
        ),

        // MARK: Extended US stock catalogue

        Stock(symbol: "AMZN", name: "Amazon.com Inc.",
              summary: "American e-commerce and cloud-computing giant. Owns AWS, Prime Video, Whole Foods and Twitch.",
              category: .stock, fallbackPrice: 188.40, fallbackChangePercent:  1.62, fallbackCurrency: "USD"),
        Stock(symbol: "GOOGL", name: "Alphabet Inc. (Class A)",
              summary: "Parent company of Google, YouTube, Android and Waymo. Dominant in search, online advertising and Android mobile OS.",
              category: .stock, fallbackPrice: 175.20, fallbackChangePercent:  0.95, fallbackCurrency: "USD"),
        Stock(symbol: "META", name: "Meta Platforms Inc.",
              summary: "Parent of Facebook, Instagram, WhatsApp and Reality Labs. Largest social-media and digital-advertising company in the West.",
              category: .stock, fallbackPrice: 502.10, fallbackChangePercent:  2.30, fallbackCurrency: "USD"),
        Stock(symbol: "NFLX", name: "Netflix Inc.",
              summary: "American streaming-media and production company. One of the largest paid subscription video platforms worldwide.",
              category: .stock, fallbackPrice: 678.40, fallbackChangePercent: -0.74, fallbackCurrency: "USD"),
        Stock(symbol: "AMD", name: "Advanced Micro Devices",
              summary: "American semiconductor company designing CPUs, GPUs and data-centre chips. NVIDIA's primary competitor in discrete GPUs.",
              category: .stock, fallbackPrice: 162.30, fallbackChangePercent:  3.10, fallbackCurrency: "USD"),
        Stock(symbol: "INTC", name: "Intel Corp.",
              summary: "American chip manufacturer behind the x86 architecture, Core processors and Intel Foundry Services.",
              category: .stock, fallbackPrice:  31.20, fallbackChangePercent: -1.85, fallbackCurrency: "USD"),
        Stock(symbol: "ORCL", name: "Oracle Corp.",
              summary: "American enterprise-software and cloud-infrastructure company best known for its database and ERP products.",
              category: .stock, fallbackPrice: 142.70, fallbackChangePercent:  0.81, fallbackCurrency: "USD"),
        Stock(symbol: "CRM", name: "Salesforce Inc.",
              summary: "American cloud-based CRM platform vendor. Pioneer of the SaaS business model.",
              category: .stock, fallbackPrice: 264.10, fallbackChangePercent:  1.05, fallbackCurrency: "USD"),
        Stock(symbol: "ADBE", name: "Adobe Inc.",
              summary: "American software company behind Photoshop, Illustrator, Premiere Pro and the Creative Cloud subscription suite.",
              category: .stock, fallbackPrice: 532.50, fallbackChangePercent: -0.42, fallbackCurrency: "USD"),
        Stock(symbol: "CSCO", name: "Cisco Systems",
              summary: "American networking-hardware and enterprise-software company. Backbone of much of the world's internet infrastructure.",
              category: .stock, fallbackPrice:  48.90, fallbackChangePercent:  0.21, fallbackCurrency: "USD"),
        Stock(symbol: "IBM", name: "International Business Machines",
              summary: "American technology company focused on hybrid cloud, AI (Watson) and consulting services.",
              category: .stock, fallbackPrice: 175.60, fallbackChangePercent:  0.55, fallbackCurrency: "USD"),
        Stock(symbol: "JPM", name: "JPMorgan Chase",
              summary: "Largest US bank by assets. Provides retail banking, investment banking, asset management and treasury services worldwide.",
              category: .stock, fallbackPrice: 218.40, fallbackChangePercent:  0.72, fallbackCurrency: "USD"),
        Stock(symbol: "BAC", name: "Bank of America",
              summary: "Major US multinational bank and financial holding company headquartered in Charlotte, North Carolina.",
              category: .stock, fallbackPrice:  42.10, fallbackChangePercent: -0.34, fallbackCurrency: "USD"),
        Stock(symbol: "V", name: "Visa Inc.",
              summary: "American multinational payment-card services corporation. Runs one of the largest electronic-payment networks in the world.",
              category: .stock, fallbackPrice: 282.30, fallbackChangePercent:  0.62, fallbackCurrency: "USD"),
        Stock(symbol: "MA", name: "Mastercard Inc.",
              summary: "American multinational payment-processing company. Operator of the second-largest global card-payments network after Visa.",
              category: .stock, fallbackPrice: 482.20, fallbackChangePercent:  0.81, fallbackCurrency: "USD"),
        Stock(symbol: "DIS", name: "The Walt Disney Co.",
              summary: "American mass-media and entertainment conglomerate behind Disney+, ESPN, Marvel, Pixar, Lucasfilm and the theme parks.",
              category: .stock, fallbackPrice: 105.60, fallbackChangePercent: -0.12, fallbackCurrency: "USD"),
        Stock(symbol: "KO", name: "The Coca-Cola Co.",
              summary: "American multinational beverage company. Maker of Coca-Cola, Fanta, Sprite and hundreds of other brands.",
              category: .stock, fallbackPrice:  68.20, fallbackChangePercent:  0.18, fallbackCurrency: "USD"),
        Stock(symbol: "PEP", name: "PepsiCo Inc.",
              summary: "American multinational food and beverage company. Brands include Pepsi, Lay's, Doritos, Quaker Oats and Gatorade.",
              category: .stock, fallbackPrice: 168.40, fallbackChangePercent: -0.21, fallbackCurrency: "USD"),
        Stock(symbol: "MCD", name: "McDonald's Corp.",
              summary: "American fast-food chain operating the world's largest restaurant network by revenue.",
              category: .stock, fallbackPrice: 292.10, fallbackChangePercent:  0.42, fallbackCurrency: "USD"),
        Stock(symbol: "NKE", name: "Nike Inc.",
              summary: "American multinational athletic-footwear, apparel and equipment brand. World's largest sports-goods supplier.",
              category: .stock, fallbackPrice:  78.30, fallbackChangePercent: -0.92, fallbackCurrency: "USD"),
        Stock(symbol: "WMT", name: "Walmart Inc.",
              summary: "American multinational retail corporation operating the world's largest chain of hypermarkets and grocery stores.",
              category: .stock, fallbackPrice:  74.60, fallbackChangePercent:  0.32, fallbackCurrency: "USD"),
        Stock(symbol: "JNJ", name: "Johnson & Johnson",
              summary: "American multinational pharmaceutical and medical-devices company. One of the largest healthcare firms in the world.",
              category: .stock, fallbackPrice: 162.40, fallbackChangePercent: -0.18, fallbackCurrency: "USD"),
        Stock(symbol: "PFE", name: "Pfizer Inc.",
              summary: "American multinational pharmaceutical and biotechnology corporation behind many widely used vaccines and medicines.",
              category: .stock, fallbackPrice:  28.90, fallbackChangePercent: -0.45, fallbackCurrency: "USD"),
        Stock(symbol: "XOM", name: "Exxon Mobil",
              summary: "American multinational oil and gas company. One of the world's largest publicly traded energy companies.",
              category: .stock, fallbackPrice: 118.50, fallbackChangePercent:  0.86, fallbackCurrency: "USD"),
        Stock(symbol: "CVX", name: "Chevron Corp.",
              summary: "American multinational energy corporation engaged in oil, natural gas and geothermal energy.",
              category: .stock, fallbackPrice: 158.20, fallbackChangePercent:  0.51, fallbackCurrency: "USD"),
        Stock(symbol: "BA", name: "The Boeing Co.",
              summary: "American multinational aerospace company. Largest exporter in the United States by dollar value.",
              category: .stock, fallbackPrice: 184.30, fallbackChangePercent: -1.20, fallbackCurrency: "USD"),
        Stock(symbol: "BRK-B", displaySymbol: "BRK.B",
              name: "Berkshire Hathaway (Class B)",
              summary: "American multinational holding company chaired by Warren Buffett. Owns GEICO, BNSF Railway, See's Candies and stakes in Apple and Coca-Cola.",
              category: .stock, fallbackPrice: 432.80, fallbackChangePercent:  0.41, fallbackCurrency: "USD"),
        Stock(symbol: "UBER", name: "Uber Technologies",
              summary: "American mobility and delivery platform. Operates ride-hailing, Uber Eats and Uber Freight globally.",
              category: .stock, fallbackPrice:  72.10, fallbackChangePercent:  1.42, fallbackCurrency: "USD"),
        Stock(symbol: "PYPL", name: "PayPal Holdings",
              summary: "American multinational fintech company operating online payments and Venmo.",
              category: .stock, fallbackPrice:  72.40, fallbackChangePercent: -0.31, fallbackCurrency: "USD"),
        Stock(symbol: "SHOP", name: "Shopify Inc.",
              summary: "Canadian multinational e-commerce platform provider powering millions of online stores worldwide.",
              category: .stock, fallbackPrice:  92.80, fallbackChangePercent:  2.10, fallbackCurrency: "USD"),
        Stock(symbol: "COIN", name: "Coinbase Global",
              summary: "American publicly listed cryptocurrency exchange. Largest US crypto trading venue.",
              category: .stock, fallbackPrice: 218.40, fallbackChangePercent:  3.42, fallbackCurrency: "USD"),
        Stock(symbol: "PLTR", name: "Palantir Technologies",
              summary: "American software company specialising in big-data analytics for government and commercial customers.",
              category: .stock, fallbackPrice:  42.80, fallbackChangePercent:  2.85, fallbackCurrency: "USD"),
        Stock(symbol: "BABA", name: "Alibaba Group",
              summary: "Chinese multinational e-commerce and cloud-computing conglomerate. Operates Taobao, Tmall and Alibaba Cloud.",
              category: .stock, fallbackPrice:  82.10, fallbackChangePercent: -0.62, fallbackCurrency: "USD"),

        // MARK: Extended German (Xetra) stock catalogue

        Stock(symbol: "DTE.DE", displaySymbol: "DTE",
              name: "Deutsche Telekom AG",
              summary: "German telecommunications company headquartered in Bonn. Largest telecom provider in Europe by revenue; majority owner of T-Mobile US.",
              category: .stock, fallbackPrice:  28.40, fallbackChangePercent:  0.31, fallbackCurrency: "EUR"),
        Stock(symbol: "MUV2.DE", displaySymbol: "MUV2",
              name: "Münchener Rück (Munich Re)",
              summary: "German multinational reinsurance company headquartered in Munich. One of the world's leading reinsurers.",
              category: .stock, fallbackPrice: 498.20, fallbackChangePercent:  0.45, fallbackCurrency: "EUR"),
        Stock(symbol: "RWE.DE", displaySymbol: "RWE",
              name: "RWE AG",
              summary: "German multinational energy company. Major operator of renewable and conventional power-generation assets across Europe.",
              category: .stock, fallbackPrice:  32.10, fallbackChangePercent: -0.62, fallbackCurrency: "EUR"),
        Stock(symbol: "ADS.DE", displaySymbol: "ADS",
              name: "adidas AG",
              summary: "German multinational sportswear corporation headquartered in Herzogenaurach. Second-largest sportswear maker after Nike.",
              category: .stock, fallbackPrice: 232.50, fallbackChangePercent:  1.21, fallbackCurrency: "EUR"),
        Stock(symbol: "BAS.DE", displaySymbol: "BAS",
              name: "BASF SE",
              summary: "German multinational chemical company headquartered in Ludwigshafen. Largest chemical producer in the world by revenue.",
              category: .stock, fallbackPrice:  48.60, fallbackChangePercent: -0.32, fallbackCurrency: "EUR"),
        Stock(symbol: "DBK.DE", displaySymbol: "DBK",
              name: "Deutsche Bank AG",
              summary: "German multinational investment bank and financial-services company headquartered in Frankfurt.",
              category: .stock, fallbackPrice:  16.40, fallbackChangePercent:  0.92, fallbackCurrency: "EUR"),
        Stock(symbol: "IFX.DE", displaySymbol: "IFX",
              name: "Infineon Technologies",
              summary: "German semiconductor manufacturer. World leader in power chips and automotive microcontrollers.",
              category: .stock, fallbackPrice:  32.80, fallbackChangePercent:  1.85, fallbackCurrency: "EUR"),
        Stock(symbol: "LIN.DE", displaySymbol: "LIN",
              name: "Linde plc",
              summary: "Multinational industrial-gases and engineering company. Largest industrial-gas supplier in the world by revenue.",
              category: .stock, fallbackPrice: 462.40, fallbackChangePercent:  0.52, fallbackCurrency: "EUR"),
        Stock(symbol: "MBG.DE", displaySymbol: "MBG",
              name: "Mercedes-Benz Group",
              summary: "German multinational luxury automotive company. Designs and manufactures Mercedes-Benz, Maybach and AMG vehicles.",
              category: .stock, fallbackPrice:  62.80, fallbackChangePercent: -0.41, fallbackCurrency: "EUR"),
        Stock(symbol: "MRK.DE", displaySymbol: "MRK",
              name: "Merck KGaA",
              summary: "German multinational science and technology company. Active in healthcare, life-science and electronic materials.",
              category: .stock, fallbackPrice: 168.20, fallbackChangePercent:  0.31, fallbackCurrency: "EUR"),
        Stock(symbol: "P911.DE", displaySymbol: "P911",
              name: "Porsche AG",
              summary: "German luxury-sports-car manufacturer headquartered in Stuttgart-Zuffenhausen. Subsidiary of Volkswagen AG.",
              category: .stock, fallbackPrice:  74.60, fallbackChangePercent: -0.85, fallbackCurrency: "EUR"),
        Stock(symbol: "AIR.DE", displaySymbol: "AIR",
              name: "Airbus SE",
              summary: "European multinational aerospace corporation. Largest aircraft manufacturer in the world by deliveries.",
              category: .stock, fallbackPrice: 152.40, fallbackChangePercent:  0.62, fallbackCurrency: "EUR"),
        Stock(symbol: "DHL.DE", displaySymbol: "DHL",
              name: "Deutsche Post DHL",
              summary: "German multinational logistics company. World's largest courier operator and parcel-delivery provider.",
              category: .stock, fallbackPrice:  38.60, fallbackChangePercent:  0.21, fallbackCurrency: "EUR"),

        // MARK: Extended UK/European stocks

        Stock(symbol: "SHEL.L", displaySymbol: "SHEL",
              name: "Shell plc",
              summary: "British multinational oil-and-gas company headquartered in London. One of the supermajor energy companies.",
              category: .stock, fallbackPrice:  28.40, fallbackChangePercent:  0.42, fallbackCurrency: "GBP"),
        Stock(symbol: "AZN.L", displaySymbol: "AZN",
              name: "AstraZeneca plc",
              summary: "British-Swedish multinational pharmaceutical and biotechnology company. Major producer of oncology and respiratory medicines.",
              category: .stock, fallbackPrice: 124.50, fallbackChangePercent: -0.31, fallbackCurrency: "GBP"),
        Stock(symbol: "HSBA.L", displaySymbol: "HSBA",
              name: "HSBC Holdings",
              summary: "British multinational banking and financial-services holding company. One of the largest banks in Europe by assets.",
              category: .stock, fallbackPrice:   7.20, fallbackChangePercent:  0.62, fallbackCurrency: "GBP"),
        Stock(symbol: "NESN.SW", displaySymbol: "NESN",
              name: "Nestlé SA",
              summary: "Swiss multinational food-and-drink conglomerate headquartered in Vevey. Largest publicly held food company in the world.",
              category: .stock, fallbackPrice:  84.20, fallbackChangePercent: -0.22, fallbackCurrency: "CHF"),
        Stock(symbol: "NOVO-B.CO", displaySymbol: "NOVO-B",
              name: "Novo Nordisk",
              summary: "Danish multinational pharmaceutical company. Global leader in diabetes care and GLP-1 obesity medications (Ozempic, Wegovy).",
              category: .stock, fallbackPrice: 124.80, fallbackChangePercent:  1.21, fallbackCurrency: "USD"),

        // MARK: Extended ETF catalogue (Xetra / EU)

        Stock(symbol: "IUSQ.DE", displaySymbol: "IUSQ",
              name: "iShares MSCI ACWI UCITS ETF",
              summary: "Tracks the MSCI All Country World Index — ~2,900 large- and mid-cap stocks across both developed and emerging markets.",
              category: .etf, fallbackPrice:  82.40, fallbackChangePercent:  0.62, fallbackCurrency: "EUR"),
        Stock(symbol: "XAIX.DE", displaySymbol: "XAIX",
              name: "Xtrackers AI & Big Data ETF",
              summary: "Thematic ETF tracking companies active in artificial intelligence and big-data analytics.",
              category: .etf, fallbackPrice:  68.20, fallbackChangePercent:  1.32, fallbackCurrency: "EUR"),
        Stock(symbol: "EXSA.DE", displaySymbol: "EXSA",
              name: "iShares STOXX Europe 600",
              summary: "Tracks the STOXX Europe 600 — 600 large-, mid- and small-cap companies across 17 European countries.",
              category: .etf, fallbackPrice:  52.80, fallbackChangePercent:  0.45, fallbackCurrency: "EUR"),
        Stock(symbol: "AGGH.DE", displaySymbol: "AGGH",
              name: "iShares Core Global Aggregate Bond",
              summary: "Tracks the Bloomberg Global Aggregate Bond index — investment-grade government and corporate bonds globally, EUR-hedged.",
              category: .etf, fallbackPrice:   4.62, fallbackChangePercent: -0.08, fallbackCurrency: "EUR"),
        Stock(symbol: "EUNA.DE", displaySymbol: "EUNA",
              name: "iShares Core EURO STOXX 50",
              summary: "Tracks the EURO STOXX 50 — 50 largest blue-chip companies from 11 eurozone countries.",
              category: .etf, fallbackPrice: 152.40, fallbackChangePercent:  0.32, fallbackCurrency: "EUR"),
        Stock(symbol: "QDVE.DE", displaySymbol: "QDVE",
              name: "iShares S&P 500 IT Sector",
              summary: "Sector ETF tracking the S&P 500 Information Technology Index — concentrated US large-cap tech exposure.",
              category: .etf, fallbackPrice:  22.40, fallbackChangePercent:  1.10, fallbackCurrency: "EUR"),
        Stock(symbol: "ZPRV.DE", displaySymbol: "ZPRV",
              name: "SPDR MSCI USA Small-Cap Value",
              summary: "Factor ETF tracking small-cap US value stocks following the MSCI USA Small Cap Value Weighted index.",
              category: .etf, fallbackPrice:  68.10, fallbackChangePercent:  0.42, fallbackCurrency: "EUR"),
        Stock(symbol: "WSML.L", displaySymbol: "WSML",
              name: "iShares MSCI World Small Cap",
              summary: "Tracks the MSCI World Small Cap index — small-cap exposure across developed markets, common diversifier on top of MSCI World.",
              category: .etf, fallbackPrice:   6.20, fallbackChangePercent:  0.21, fallbackCurrency: "USD"),
    ]

    /// The default watchlist a brand-new user starts with on first launch.
    static let defaultWatchlistSymbols: [String] = [
        "AAPL", "TSLA", "MSFT", "NVDA", "ASML", "SAP.DE", "ALV.DE",
        "VWCE.DE", "EUNL.DE", "SXR8.DE",
    ]

    /// Lookup helper.
    static func stock(forSymbol symbol: String) -> Stock? {
        catalog.first { $0.symbol == symbol }
    }
}
